name: deploy

on:
  release:
    types: [published]

jobs:
  deploy:
    concurrency: release
    runs-on: 'ubuntu-latest'
    environment: 'staging'
    if: github.run_attempt == 1
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1.8.0
        with:
          app_id: ${{ secrets.PROGRAMEH_BOT_ID }}
          private_key: ${{ secrets.PROGRAMEH_BOT_PRIVATE_ACCESS_KEY }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: setup terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: terraform init
        id: init
        run: terraform init
      - name: Download Asset
        uses: robinraju/release-downloader@v1.8
        with:
            repository: programeh/Infra-Configuration
            tag: ${{ github.event.release.name }}
            fileName: diff.zip
            token: ${{ steps.generate_token.outputs.token }}
      - name: unzip file
        run: |
          unzip diff.zip 

      - name: terraform apply
        id: apply
        run: terraform apply workspace.plan --auto-approve
