name: deploy

on:
  release:
    types: [published]

jobs:
  deploy:
    concurrency: release
    runs-on: 'ubuntu-latest'
    environment: 'staging'
    if: github.run_attempt == 1
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: 'ap-south-1'
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1.8.0
        with:
          app_id: ${{ secrets.PROGRAMEH_BOT_ID }}
          private_key: ${{ secrets.PROGRAMEH_BOT_PRIVATE_ACCESS_KEY }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: setup terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: terraform init
        id: init
        run: terraform init
      - name: terraform apply
        id: plan
        run: terraform apply --auto-approve
